export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/auth/me",
    profile: "/auth/profile",
    requestPasswordReset: "/auth/request-password-reset",
    resetPassword: "/auth/reset-password",
  },
  users: {
    list: "/users",
    update: (id: string) => `/users/${id}`,
  },
  business: {
    create: "/business",
    list: "/business",
    getById: (id: string) => `/business/${id}`,
    update: (id: string) => `/business/${id}`,
    selectApps: "/business/apps",
  },
  categories: {
    create: "/product-categories",
    list: "/product-categories",
    getById: (id: string) => `/product-categories/${id}`,
    update: (id: string) => `/api/product-categories/${id}`,
    delete: (id: string) => `/product-categories/${id}`,
  },
  branches: {
    create: "/branches",
    list: "/branches",
    getById: (id: string) => `/branches/${id}`,
    update: (id: string) => `/branches/${id}`,
    delete: (id: string) => `/branches/${id}`,
  },
  units: {
    create: "/units",
    list: "/units",
    getById: (id: string) => `/units/${id}`,
    update: (id: string) => `/units/${id}`,
    delete: (id: string) => `/units/${id}`,
  },
  roles: {
    create: "/roles",
    list: "/roles",
    getById: (id: string) => `/roles/${id}`,
    update: (id: string) => `/roles/${id}`,
    delete: (id: string) => `/roles/${id}`,
    assignUser: (id: string) => `/roles/${id}/assign-user`,
  },
  products: {
    create: "/products",
    list: "/products",
    getById: (id: string) => `/products/${id}`,
    update: (id: string) => `/products/${id}`,
    delete: (id: string) => `/products/${id}`,
  },
  productVariants: {
    create: (productId: string) => `/product-variants/${productId}`,
    listByProduct: (productId: string) => `/product-variants/by-product/${productId}`,
    getById: (id: string) => `/product-variants/${id}`,
    update: (id: string) => `/product-variants/${id}`,
    delete: (id: string) => `/product-variants/${id}`,
  },
  attributes: {
    create: (productId: string) => `/attributes/${productId}`,
    listByProduct: (productId: string) => `/attributes/by-product/${productId}`,
    update: (id: string) => `/attributes/${id}`,
    delete: (id: string) => `/attributes/${id}`,
  },
  stocks: {
    list: "/stocks",
    create: "/stocks",
    getById: (id: string) => `/stocks/${id}`,
    listByBranch: (branchId: string) => `/stocks/by-branch/${branchId}`,
    listByProduct: (productId: string) => `/api/stocks/by-product/${productId}`,
    historyByBranch: (branchId: string) => `/stocks/history/by-branch/${branchId}`,
    historyByProduct: (productId: string) => `/stocks/history/by-product/${productId}`,
    historyByBranchAndProduct: (branchId: string, productId: string) =>
      `/stocks/history/by-branch/${branchId}/by-product/${productId}`,
    historyByStock: (stockId: string) => `/stocks/${stockId}/history`,
    adjust: "/stocks/adjust",
  },
} as const
