export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/auth/me",
    profile: "/auth/profile",
    requestPasswordReset: "/auth/request-password-reset",
    resetPassword: "/auth/reset-password",
  },
  users: {
    list: "/users",
    update: (id: string) => `/users/${id}`,
  },
  business: {
    create: "/business",
    list: "/business",
    getById: (id: string) => `/business/${id}`,
    update: (id: string) => `/business/${id}`,
    selectApps: "/business/apps",
  },
  categories: {
    create: "/product-categories",
    list: "/product-categories",
    getById: (id: string) => `/product-categories/${id}`,
    update: (id: string) => `/api/product-categories/${id}`,
    delete: (id: string) => `/product-categories/${id}`,
  },
  branches: {
    create: "/branches",
    list: "/branches",
    getById: (id: string) => `/branches/${id}`,
    update: (id: string) => `/branches/${id}`,
    delete: (id: string) => `/branches/${id}`,
  },
  units: {
    create: "/units",
    list: "/units",
    getById: (id: string) => `/units/${id}`,
    update: (id: string) => `/units/${id}`,
    delete: (id: string) => `/units/${id}`,
  },
  roles: {
    create: "/roles",
    list: "/roles",
    getById: (id: string) => `/roles/${id}`,
    update: (id: string) => `/roles/${id}`,
    delete: (id: string) => `/roles/${id}`,
    assignUser: (id: string) => `/roles/${id}/assign-user`,
  },
} as const
