export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/auth/me",
    profile: "/auth/profile",
    requestPasswordReset: "/auth/request-password-reset",
    resetPassword: "/auth/reset-password",
  },
  users: {
    list: "/users",
    update: (id: string) => `/users/${id}`,
  },
  business: {
    create: "/business",
    list: "/business",
    getById: (id: string) => `/business/${id}`,
    update: (id: string) => `/business/${id}`,
    selectApps: "/business/apps",
  },
  categories: {
    create: "/product-categories",
    list: "/product-categories",
    getById: (id: string) => `/product-categories/${id}`,
    update: (id: string) => `/api/product-categories/${id}`,
    delete: (id: string) => `/product-categories/${id}`,
  },
  branches: {
    create: "/branches",
    list: "/branches",
    getById: (id: string) => `/branches/${id}`,
    update: (id: string) => `/branches/${id}`,
    delete: (id: string) => `/branches/${id}`,
  },
  units: {
    create: "/units",
    list: "/units",
    getById: (id: string) => `/units/${id}`,
    update: (id: string) => `/units/${id}`,
    delete: (id: string) => `/units/${id}`,
  },
  roles: {
    create: "/roles",
    list: "/roles",
    getById: (id: string) => `/roles/${id}`,
    update: (id: string) => `/roles/${id}`,
    delete: (id: string) => `/roles/${id}`,
    assignUser: (id: string) => `/roles/${id}/assign-user`,
  },
  products: {
    create: "/products",
    list: "/products",
    getById: (id: string) => `/products/${id}`,
    update: (id: string) => `/products/${id}`,
    delete: (id: string) => `/products/${id}`,
  },
  productVariants: {
    create: (productId: string) => `/product-variants/${productId}`,
    listByProduct: (productId: string) => `/product-variants/by-product/${productId}`,
    getById: (id: string) => `/product-variants/${id}`,
    update: (id: string) => `/product-variants/${id}`,
    delete: (id: string) => `/product-variants/${id}`,
  },
  attributes: {
    create: "/attributes",
    list: "/attributes",
    getById: (id: string) => `/attributes/${id}`,
    update: (id: string) => `/attributes/${id}`,
    delete: (id: string) => `/attributes/${id}`,
  },
  brands: {
    create: "/brands",
    list: "/brands",
    getById: (id: string) => `/brands/${id}`,
    update: (id: string) => `/brands/${id}`,
    delete: (id: string) => `/brands/${id}`,
  },
  stocks: {
    list: "/stocks",
    create: "/stocks",
    getById: (id: string) => `/stocks/${id}`,
    update: (id: string) => `/stocks/${id}`,
    adjustments: {
      list: "/stocks/adjustments",
      create: "/stocks/adjustments",
      update: (id: string) => `/stocks/adjustments/${id}`,
    },
    history: "/stocks/history",
  },
  purchases: {
    create: "/purchases",
    list: "/purchases",
    getById: (id: string) => `/purchases/${id}`,
    update: (id: string) => `/purchases/${id}`,
    delete: (id: string) => `/purchases/${id}`,
  },
  contacts: {
    create: "/contacts",
    list: "/contacts",
    getById: (id: string) => `/contacts/${id}`,
    update: (id: string) => `/contacts/${id}`,
    delete: (id: string) => `/contacts/${id}`,
  },
  sales: {
    create: "/sales",
    list: "/sales",
    getById: (id: string) => `/sales/${id}`,
    update: (id: string) => `/sales/${id}`,
    delete: (id: string) => `/sales/${id}`,
  },
  media: {
    upload: "/media/upload",
    list: "/media",
    update: (id: string) => `/media/${id}`,
    delete: (id: string) => `/media/${id}`,
  },
} as const
