"use client"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Printer } from "lucide-react"
import { useAppSettings } from "@/lib/providers/settings-provider"
import { formatCurrency } from "@/lib/utils/currency"

export interface PaymentReceiptData {
  contactName: string
  totalPaid: number
  remainingDeposit: number
  allocations: Array<{ saleId: string; invoiceNumber: string; appliedAmount: number }>
  date: string
}

interface PaymentReceiptDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  data: PaymentReceiptData | null
}

export function PaymentReceiptDialog({
  open,
  onOpenChange,
  data,
}: PaymentReceiptDialogProps) {
  const { generalSettings } = useAppSettings()

  const handlePrint = () => {
    window.print();
  }

  if (!data) return null

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex justify-between items-center">
            <span>Payment Receipt</span>
            <Button variant="outline" size="sm" onClick={handlePrint}>
              <Printer className="w-4 h-4 mr-2" />
              Print
            </Button>
          </DialogTitle>
        </DialogHeader>

        <div className="bg-white text-black p-6 rounded-md border print:border-none print:shadow-none">
          <div className="text-center mb-6">
            <h2 className="text-2xl font-bold uppercase tracking-wider">{generalSettings?.companyName || "HAMOOD TECH"}</h2>
            <p className="text-sm text-gray-500">Payment Acknowledgment</p>
          </div>

          <div className="flex justify-between items-end border-b pb-4 mb-4">
            <div>
              <p className="text-sm text-gray-500 mb-1">Received From:</p>
              <p className="font-semibold text-lg">{data.contactName}</p>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-500 mb-1">Date:</p>
              <p className="font-medium">{new Date(data.date).toLocaleDateString()}</p>
            </div>
          </div>

          <div className="mb-6 bg-gray-50 p-4 rounded-md border">
            <p className="text-sm text-gray-500 mb-1">Total Amount Received</p>
            <p className="text-3xl font-bold text-emerald-600">
              {formatCurrency(data.totalPaid, { generalSettings })}
            </p>
          </div>

          {data.allocations.length > 0 && (
            <div className="mb-4">
              <h3 className="font-semibold mb-2 text-sm uppercase tracking-wide text-gray-600">Applied To Invoices</h3>
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b">
                    <th className="text-left pb-2 font-medium text-gray-500">Invoice No.</th>
                    <th className="text-right pb-2 font-medium text-gray-500">Amount Applied</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {data.allocations.map((alloc, idx) => (
                    <tr key={idx}>
                      <td className="py-2 font-medium text-gray-800">{alloc.invoiceNumber}</td>
                      <td className="py-2 text-right font-medium text-gray-800">
                        {formatCurrency(alloc.appliedAmount, { generalSettings })}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {data.remainingDeposit > 0 && (
            <div className="mt-4 pt-4 border-t flex justify-between items-center text-sm">
              <span className="font-medium text-gray-600">Added to Advance Balance (Deposit):</span>
              <span className="font-bold text-gray-800">{formatCurrency(data.remainingDeposit, { generalSettings })}</span>
            </div>
          )}

          <div className="mt-8 pt-4 border-t text-center text-xs text-gray-400">
            <p>Thank you for your business!</p>
            <p>Generated by HamoodTech POS</p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
